
// Neurons Calculation
#define IMAGE_INPUT_PART1     224
#define IMAGE_INPUT_PART2     112
#define IMAGE_INPUT_PART3      66
#define IMAGE_INPUT_PART4      33
#define IMAGE_INPUT_PART5      16
#define IMAGE_INPUT_PARTFC1     8
#define IMAGE_INPUT_PARTFC2  4096
#define IMAGE_INPUT_PARTFC3  4096


#define  INPUT_CHANNELS         3
#define  PART1_CHANNELS        64
#define  PART2_CHANNELS       128
#define  PART3_CHANNELS       256
#define  PART4_CHANNELS       512
#define  PART5_CHANNELS       512
#define  FC_CHANNELS         4096
#define  SFM_CHANNELS        1000

#define RGB (3)
#define KERNEL_SIZE (3*3)

// Weights Calculation
#define CONVLAYER_1_1_WEIGHTS (KERNEL_SIZE*INPUT_CHANNELS*PART1_CHANNELS)
#define CONVLAYER_1_2_WEIGHTS (PART1_CHANNELS*PART1_CHANNELS)
#define CONVLAYER_2_1_WEIGHTS (PART1_CHANNELS*PART2_CHANNELS)
#define CONVLAYER_2_2_WEIGHTS (PART2_CHANNELS*PART2_CHANNELS)
#define CONVLAYER_3_1_WEIGHTS (PART2_CHANNELS*PART3_CHANNELS)
#define CONVLAYER_3_2_WEIGHTS (PART3_CHANNELS*PART3_CHANNELS)
#define CONVLAYER_3_3_WEIGHTS (PART3_CHANNELS*PART3_CHANNELS)
#define CONVLAYER_4_1_WEIGHTS (PART3_CHANNELS*PART4_CHANNELS)
#define CONVLAYER_4_2_WEIGHTS (PART4_CHANNELS*PART4_CHANNELS)
#define CONVLAYER_4_3_WEIGHTS (PART4_CHANNELS*PART4_CHANNELS)
#define CONVLAYER_5_1_WEIGHTS (PART4_CHANNELS*PART5_CHANNELS)
#define CONVLAYER_5_2_WEIGHTS (PART5_CHANNELS*PART5_CHANNELS)
#define CONVLAYER_5_3_WEIGHTS (PART5_CHANNELS*PART5_CHANNELS)
#define FCLAYER_1_WEIGHTS (PART5_CHANNELS*PART1_CHANNELS)
#define FCLAYER_2_WEIGHTS (FC_CHANNELS*FC_CHANNELS)
#define FCLAYER_3_WEIGHTS (FC_CHANNELS*FC_CHANNELS)

//---------------------------------jean-----------------------------
#define  CONV_SIZE        3
int layers[13][4] = {
	{ 64, 3, CONV_SIZE, CONV_SIZE },
	{ 64, 64, CONV_SIZE, CONV_SIZE },
	{ 128, 64, CONV_SIZE, CONV_SIZE },
	{ 128, 128, CONV_SIZE, CONV_SIZE },
	{ 256, 128, CONV_SIZE, CONV_SIZE },
	{ 256, 256, CONV_SIZE, CONV_SIZE },
	{ 256, 256, CONV_SIZE, CONV_SIZE },
	{ 512, 256, CONV_SIZE, CONV_SIZE },
	{ 512, 512, CONV_SIZE, CONV_SIZE },
	{ 512, 512, CONV_SIZE, CONV_SIZE },
	{ 512, 512, CONV_SIZE, CONV_SIZE },
	{ 512, 512, CONV_SIZE, CONV_SIZE },
	{ 512, 512, CONV_SIZE, CONV_SIZE }
};



#define MASK_WIDTH 3
#define TILE_SIZE_1 32
